#Import the base docker image built on top of Alpine
FROM alpine:3.8 

#Add Packages
RUN apk add --no-cache bash sed grep curl coreutils nodejs yarn

WORKDIR /data
WORKDIR /props
ADD ./test/input.properties /props/
ADD ./test/uploadfile.txt /data/
WORKDIR /cli
ADD ./cli.js .
ADD ./log.js .
ADD ./props.js .
ADD ./commands ./commands
ADD ./package.json .
RUN ls -ltr
RUN yarn install && yarn link
RUN curl --version

ENTRYPOINT [ "node", "cli.js" ]