#Import the base docker image built on top of Alpine
FROM alpine:3.8 

#Add Packages
RUN apk add --no-cache bash sed grep curl coreutils nodejs yarn

WORKDIR /props
COPY ./test/input.properties ./test/output.properties ./
WORKDIR /data
COPY ./test/uploadfile.txt ./
WORKDIR /cli
ADD ./cli.js ./log.js ./utils.js ./package.json ./
ADD ./commands ./commands
RUN ls -ltr && yarn install && yarn link
RUN curl --version && less /props/output.properties && ls -ltr /cli/commands

ENTRYPOINT [ "node", "cli.js" ]