#Import the base docker image built on top of Alpine
#FROM alpine:3.8
FROM ubuntu:18.04

#Add Packages
RUN apk add --no-cache bash sed grep curl coreutils nodejs npm

COPY ./props /props/
RUN ls -ltr /props
COPY ./data/uploadfile.txt /data/
RUN ls -ltr /data
WORKDIR /cli
ADD ./cli.js ./log.js ./error.js ./utils.js ./config.js  ./package.json ./
ADD ./commands ./commands
RUN ls -ltr && npm install && npm link
RUN curl --version && ls -ltr /cli/commands
RUN mkdir /lifecycle

ENV DEBUG=true

ENTRYPOINT [ "node", "cli" ]
